version: 2

jobs:
  test_7.1:
    working_directory: ~/artisan-view
    docker:
      - image: circleci/php:7.1-fpm-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update --no-progress --no-interaction
      - run: composer install --no-progress --no-interaction --prefer-dist
      - run: ./vendor/bin/phpunit --coverage-clover=coverage.xml
      - run: bash <(curl -s https://codecov.io/bash)

  test_7.2:
    working_directory: ~/artisan-view
    docker:
      - image: circleci/php:7.2-fpm-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update --no-progress --no-interaction
      - run: composer install --no-progress --no-interaction --prefer-dist
      - run: ./vendor/bin/phpunit --coverage-clover=coverage.xml
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  test:
    jobs:
      - test_7.1
      - test_7.2
