version: 2

jobs:
  build:
    working_directory: ~/artisan-view
    docker:
      - image: circleci/7.1-cli
    steps:
      - checkout
      - run: composer self-update
      - run: composer install -n --prefer-dist
      - run: ./vendor/bin/phpunit
